### ISSUE TITLE
binary complex test with 1AVX

### ISSUE THREAD

**Issue by heejongkim** [salilab/optimal_representation#2]
After fixing minor aspects of python scripts, i was finally able to execute the following command line:

$ python3 incremental_coarse_grain_local.py -s 1AVX -e rprime -r 0 > out.txt 2>&1

Starting with the line:
Current resolution:  1

--- omitted for the sake of space limitation ---

I condensed only error msgs in between other log printouts.

/cm/shared/apps/imp/2.14.0-experimental/lib64/python3.8/site-packages/IMP/pmi/topology/__init__.py:728: StructureWarning: Residues without representation in molecule A: 1-15
  warnings.warn(
Traceback (most recent call last):
  File "/home/kim/imp_opt_paper/optimal_representation/scripts/binary_complexes/sample_rigid_to_snake.py", line 108, in <module>
    recenter(mol)
  File "/home/kim/imp_opt_paper/optimal_representation/scripts/binary_complexes/sample_rigid_to_snake.py", line 22, in recenter
    m=mol.mdl 
AttributeError: 'Molecule' object has no attribute 'mdl'
/cm/shared/apps/imp/2.14.0-experimental/lib64/python3.8/site-packages/IMP/pmi/topology/__init__.py:728: StructureWarning: Residues without representation in molecule A: 1-15
  warnings.warn(
Traceback (most recent call last):
  File "/home/kim/imp_opt_paper/optimal_representation/scripts/binary_complexes/sample_rigid_to_snake.py", line 108, in <module>
    recenter(mol)
  File "/home/kim/imp_opt_paper/optimal_representation/scripts/binary_complexes/sample_rigid_to_snake.py", line 22, in recenter
    m=mol.mdl 
AttributeError: 'Molecule' object has no attribute 'mdl'
/cm/shared/apps/imp/2.14.0-experimental/lib64/python3.8/site-packages/IMP/pmi/topology/__init__.py:728: StructureWarning: Residues without representation in molecule A: 1-15
  warnings.warn(
Traceback (most recent call last):
  File "/home/kim/imp_opt_paper/optimal_representation/scripts/binary_complexes/sample_rigid_to_snake.py", line 108, in <module>
    recenter(mol)
  File "/home/kim/imp_opt_paper/optimal_representation/scripts/binary_complexes/sample_rigid_to_snake.py", line 22, in recenter
    m=mol.mdl 
AttributeError: 'Molecule' object has no attribute 'mdl'
/cm/shared/apps/imp/2.14.0-experimental/lib64/python3.8/site-packages/IMP/pmi/topology/__init__.py:728: StructureWarning: Residues without representation in molecule A: 1-15
  warnings.warn(
Traceback (most recent call last):
  File "/home/kim/imp_opt_paper/optimal_representation/scripts/binary_complexes/sample_rigid_to_snake.py", line 108, in <module>
    recenter(mol)
  File "/home/kim/imp_opt_paper/optimal_representation/scripts/binary_complexes/sample_rigid_to_snake.py", line 22, in recenter
    m=mol.mdl 
AttributeError: 'Molecule' object has no attribute 'mdl'
wc: output/stat_replica.0.out: No such file or directory
Traceback (most recent call last):
  File "incremental_coarse_grain_local.py", line 190, in <module>
    incremental_coarse_grain()
  File "incremental_coarse_grain_local.py", line 115, in incremental_coarse_grain
    num_lines_sampling_file = int(subprocess.check_output(['wc','-l','output/stat_replica.0.out']).strip().split()[0]) 
  File "/cm/shared/apps/python-3.8.7-experimental/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/cm/shared/apps/python-3.8.7-experimental/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['wc', '-l', 'output/stat_replica.0.out']' returned non-zero exit status 1.

It seems like module is not properly created so that sampling wasn't performed properly?
So, in the end, no output folder created and failed with wc -l command.
Any suggestions to fix the issue?
(maybe having python 3 causes deeper issue besides print function?)

Thanks.

**Comment by shruthivis** [comment]
the add_representation step (line 96 in https://github.com/salilab/optimal_representation/blob/master/scripts/binary_complexes/sample_rigid_to_snake.py) seems to have failed to create molecules. I guess the optrep module was not correctly set up? @heejongkim I am emailing you offline to sort this out.
